server:
  port: 8888
security:
  oauth2:
    authorization:
      check-token-access: true

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/zwj?serverTimezone=UTC&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 10000ms